apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: v1.25.0
networking:
  podSubnet: 10.244.0.0/16,2001:db8:42:0::/56
  serviceSubnet: 10.96.0.0/16,2001:db8:42:1::/112
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
nodeRegistration:
  criSocket: unix:///var/run/crio/crio.sock
localAPIEndpoint:
  advertiseAddress: 51.195.116.80
  bindPort: 6443
nodeRegistration:
  kubeletExtraArgs:
    node-ip: 51.195.116.80,2001:41d0:701:1100::5901
