---

- name: Test connection with ping
  ansible.builtin.ping:

- name: Download tigera-operator.yaml to ansible host
  remote_user: p
  become: no
  delegate_to: 127.0.0.1
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/projectcalico/calico/v3.25.0-0.dev/manifests/tigera-operator.yaml
#    url: https://raw.githubusercontent.com/projectcalico/calico/v3.24.5/manifests/tigera-operator.yaml
    dest: /tmp/tigera-operator.yaml
    owner: p
    group: p
    mode: '0644'
  when: inventory_hostname in groups.control1

- name: kubectl create -f tigera-operator.yaml
  remote_user: p
  become: no
  delegate_to: 127.0.0.1
  ansible.builtin.command:
    cmd: /usr/bin/kubectl --kubeconfig /home/p/.kube/config create -f /tmp/tigera-operator.yaml
  register: kubectl_create_operator
  when: inventory_hostname in groups.control1

- name: Print 'kubectl create -f tigera-operator.yaml' output
  ansible.builtin.debug:
    var: kubectl_create_operator.stdout_lines
  when: inventory_hostname in groups.control1

- name: Pause for 10 seconds
  ansible.builtin.pause:
    seconds: 10

- name: kubectl create -f custom-resources.yaml
  remote_user: p
  become: no
  delegate_to: 127.0.0.1
  ansible.builtin.command:
    cmd: /usr/bin/kubectl --kubeconfig /home/p/.kube/config create -f /home/p/alpine-k8s/files/custom-resources.yaml
  register: kubectl_create_custom
  when: inventory_hostname in groups.control1

- name: Print 'kubectl create -f custom-resources.yaml' output
  ansible.builtin.debug:
    var: kubectl_create_custom.stdout_lines
  when: inventory_hostname in groups.control1

- name: Pause for 10 seconds
  ansible.builtin.pause:
    seconds: 10

- name: Get kubectl get pod
  remote_user: p
  become: no
  delegate_to: 127.0.0.1
  ansible.builtin.command:
    cmd: /usr/bin/kubectl --kubeconfig /home/p/.kube/config get pod --all-namespaces -owide
  register: get_pods
  when: inventory_hostname in groups.control1

- name: Print kubectl get po output
  ansible.builtin.debug:
    var: get_pods.stdout_lines
  when: inventory_hostname in groups.control1

- name: ln -s /opt/cni/bin/calico /usr/libexec/cni/calico
  ansible.builtin.command: ln -s /opt/cni/bin/calico /usr/libexec/cni/calico

- name: ln -s /opt/cni/bin/calico-ipam /usr/libexec/cni/calico-ipam
  ansible.builtin.command: ln -s /opt/cni/bin/calico-ipam /usr/libexec/cni/calico-ipam

- name: ln -s /opt/cni/bin/flannel /usr/libexec/cni/flannel
  ansible.builtin.command: ln -s /opt/cni/bin/flannel /usr/libexec/cni/flannel

- name: service crio restart
  ansible.builtin.command: /sbin/service crio restart

- name: service kubelet restart
  ansible.builtin.command: /sbin/service kubelet restart

- name: Pause for 30 seconds
  ansible.builtin.pause:
    seconds: 30

- name: Get kubectl get no
  remote_user: p
  become: no
  delegate_to: 127.0.0.1
  ansible.builtin.command:
    cmd: /usr/bin/kubectl --kubeconfig /home/p/.kube/config get no -owide
  register: kubectl_getno_output
  when: inventory_hostname in groups.control1

- name: Print kubectl get no output
  ansible.builtin.debug:
    var: kubectl_getno_output.stdout_lines
  when: inventory_hostname in groups.control1

- name: Get kubectl get pod
  remote_user: p
  become: no
  delegate_to: 127.0.0.1
  ansible.builtin.command:
    cmd: /usr/bin/kubectl --kubeconfig /home/p/.kube/config get pod --all-namespaces -owide
  register: get_pods
  when: inventory_hostname in groups.control1

- name: Print kubectl get po output
  ansible.builtin.debug:
    var: get_pods.stdout_lines
  when: inventory_hostname in groups.control1
